apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: bitnami/openldap:latest
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        volumeMounts:
        - name: ldap-config
          mountPath: /etc/ldap.conf
          subPath: ldap.conf
        - name: ldap-data
          mountPath: /bitnami/openldap
        - name: ldap-users
          mountPath: /ldifs/users.ldif  # Mount the LDIF file
          subPath: users.ldif
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "1"
            ephemeral-storage: "2Gi"
      volumes:
      - name: ldap-config
        configMap:
          name: ldap-config
      - name: ldap-users
        configMap:
          name: ldap-users
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
  namespace: default
spec:
  selector:
    app: ldap
  ports:
    - protocol: TCP
      port: 1389
      targetPort: 1389
      name: ldap
    - protocol: TCP
      port: 1636
      targetPort: 1636
      name: ldaps
  type: ClusterIP
